default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: skip_trace_book_development
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASS"] %>
  host: localhost
  
test:
  <<: *default
  database: skip_trace_book_test
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASS"] %>

production:
  <<: *default
  database: skip_trace_book_production
  username:
  password: